atik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main.views import ProductAPIView


urlpatterns = [
    path('moder/', admin.site.urls),
    path('', include('main.urls')),
    path('admin/', include('moderator.urls')),
    path('api/v1/productlist', ProductAPIView.as_view() )


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, re_path
from . import views
app_name = 'main'
urlpatterns = [


    path('', views.main, name='main'),
    path('menu/', views.ProductAPIView.as_view(), name='menu'),
    path('menu/category/<str:slug>', views.ProductAPIView.as_view(), name='menu_cat'),
    path('menu/page/<int:page>/', views.ProductAPIView.as_view(),  name='paginator'),
    path('cool_baskets/add/<int:product_id>/', views.cool_basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>', views.cool_basket_remove, name='basket_remove'),
    path('basket', views.cool_profile, name='basket')

]

main/models.py
from django.db import models
from django.urls import reverse



class Product(models.Model):
    name = models.CharField(max_length=45)
    anons = models.CharField(max_length=150)
    status = models.BooleanField(default=True)
    image = models.ImageField(upload_to='images/')
    price = models.DecimalField(max_digits=10, decimal_places=0)
    slug = models.SlugField(max_length=125, null=True)
    cat = models.ForeignKey('Category', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('menu', kwargs={'post_slug' : self.slug})
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=45, verbose_name='Category name')
    slug = models.SlugField(max_length=125)

    def __str__(self):
        return f'{self.name}'
    def get_absolute_url(self):
        return f'/menu/category/{self.slug}'
class BasketQuerySet(models.QuerySet):
    def total_sum(self):

        return sum(x.sum() for x in self)

    def total_quantity(self):


        return sum(x.quantity for x in self)



class BasketCool(models.Model):
    user = models.CharField(max_length=200)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE, related_name='cool_product')
    quantity = models.PositiveSmallIntegerField(default=0)
    create_timestam = models.DateTimeField(auto_now_add=True)
    #objects = BasketQuerySet.as_manager()


    def sum(self):
        return self.product.price * self.quantity
    def get_absolute_url(self):
        return f'/menu/category/{self.slug}'

main/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.forms import ModelForm
from django import forms
from .models import *
class ProductForm(ModelForm):
    '''name = forms.CharField(max_length=45, widget=forms.TextInput(attrs={'type': 'text',
                                                         'id': 'name',
                                                         'name':'name',
                                                         'class': 'w-full bg-gray-800 rounded border border-gray-700 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-900 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out'}))
    anons = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'id': 'name',
                                                                          'name':'name',
                                                                          'class':'w-full bg-gray-800 rounded border border-gray-700 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-900 h-32 text-base outline-none text-gray-100 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400',
                                                         'id':'file_input',
                                                   'type':'file'}))
    price = forms.IntegerField(widget=forms.TextInput(attrs={'type': 'number',
                                                         'id': 'name',
                                                         'name':'name',
                                                         'class': 'w-full bg-gray-800 rounded border border-gray-700 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-900 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out'}))'''
    #cat = forms.ChoiceField(widget=forms.ChoiceField(attrs={'id':'category'}))
    class Meta:
        model = Product
        fields = ('name', 'anons', 'status', 'image', 'price', 'cat', )

class ProductChangeForm(ModelForm):
    name = forms.CharField(max_length=45, widget=forms.TextInput(attrs={'type': 'text',
                                                                        'id': 'name',
                                                                        'name': 'name',
                                                                        'class': 'w-full bg-gray-800 rounded border border-gray-700 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-900 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out'}))
    anons = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'id': 'name',
                                                                          'name': 'name',
                                                                          'class': 'w-full bg-gray-800 rounded border border-gray-700 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-900 h-32 text-base outline-none text-gray-100 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400',
        'id': 'file_input',
        'type': 'file'}))
    price = forms.IntegerField(widget=forms.TextInput(attrs={'type': 'number',
                                                             'id': 'name',
                                                             'name': 'name',
                                                             'class': 'w-full bg-gray-800 rounded border border-gray-700 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-900 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out'}))

    # cat = forms.ChoiceField(widget=forms.ChoiceField(attrs={'id':'category'}))
    class Meta:
        model = Product
        fields = ('name', 'anons', 'status', 'image', 'price', 'cat',)

main/views.py
import uuid
from rest_framework import generics
from django.db.models import Max, Min
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from rest_framework.response import Response

from .serializers import ProductSerializer
# Create your views here.
from rest_framework.views import APIView
from django.core.paginator import Paginator
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from django.shortcuts import render
from functools import reduce

from main.models import *


# Create your views here.


def cool_profile(request):
    def count_elements(lst):
        return {i: lst.count(i) for i in lst}

    products_id = count_elements(request.session['basket'])
    products = map(lambda x: Product.objects.get(id=x), products_id.keys())

    basket = BasketCool.objects.filter(user=request.session['username'])

    if request.session['basket'] == []:
        total_sum = 0
        total_quantity = 0
    else:
        products_id = count_elements(request.session['basket'])
        products = list(map(lambda x: Product.objects.get(id=x), products_id.keys()))
        basket = BasketCool.objects.filter(user=request.session['username'])
        products = list(zip(products_id, products))
        price_in_id = {}

        for x in products_id:
            if x in price_in_id.keys():
                price_in_id[x] = price_in_id.get(x)+1
            price_in_id[int(Product.objects.get(id=x).price*products_id.get(x))] = x
        total_sum = price_in_id.items()
        total_sum = reduce(lambda x, y: (x[0] * x[1]) + (y[0] * y[1]), list(price_in_id.items()))
        total_quantity = sum(products_id.values())
    return render(request, 'main/basket.html',
                  {'products': products, 'basket': basket, 'total_sum': total_sum, 'total_quantity': total_quantity})

'''def menu(request, slug=None , page=1):

    max_price = Product.objects.aggregate(Max('price', default=0))
    min_price = Product.objects.aggregate(Min('price', default=0))
    price_data = {'min_price':list(min_price.values())[0],'max_price':list(max_price.values())[0] }
    search_value = request.GET.get("search")
    min_pricee = request.GET.get('min_price')
    max_pricee = request.GET.get('max_price')
    query_data = {}
    product = Product.objects.all()
    if max_pricee:
        query_data['max_price'] = max_pricee
        product = product.filter(price__lte=max_pricee)
    if min_pricee:
        query_data['min_price'] = min_pricee
        product = product.filter(price__gte=min_pricee)
    if slug:
        category = Category.objects.get(slug=slug)
        product = product.filter(cat=category)
    if search_value !='' and search_value:
        query_data['search_value'] = search_value
        product = product.filter(name__contains=search_value)

    if request.GET.get('sort_method') == 'up':
        product.order_by('price')
    elif request.GET.get('sort_method') == 'down':
        product.order_by('-price')


    paginator = Paginator(object_list=product, per_page=9)
    products_paginator = paginator.page(page)
    context={'category':Category.objects.all(), 'product': products_paginator, 'price_data':price_data, 'query_data':query_data}

    return render(request, 'main/menu.html', context=context)'''
'''class ProductAPIView(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer'''
class ProductAPIView(APIView):
    def get(self, request):
        product = Product.objects.all()
        return Response({'title':"It's a get request", 'product':ProductSerializer(product, many=True).data})
    def post(self, request):
        return Response({'title': "It's a post request"})

class ProductAPIView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'main/menu.html'
    def get(self, request, slug=None, page=1):
        max_price = Product.objects.aggregate(Max('price', default=0))
        min_price = Product.objects.aggregate(Min('price', default=0))
        price_data = {'min_price': list(min_price.values())[0], 'max_price': list(max_price.values())[0]}
        search_value = request.GET.get("search")
        min_pricee = request.GET.get('min_price')
        max_pricee = request.GET.get('max_price')
        query_data = {}
        product = Product.objects.all()
        if max_pricee:
            query_data['max_price'] = max_pricee
            product = product.filter(price__lte=max_pricee)
        if min_pricee:
            query_data['min_price'] = min_pricee
            product = product.filter(price__gte=min_pricee)
        if slug:
            category = Category.objects.get(slug=slug)
            product = product.filter(cat=category)
        if search_value != '' and search_value:
            query_data['search_value'] = search_value
            product = product.filter(name__contains=search_value)

        if request.GET.get('sort_method') == 'up':
            product.order_by('price')
        elif request.GET.get('sort_method') == 'down':
            product.order_by('-price')
        product = ProductSerializer(product, many=True).data
        paginator = Paginator(object_list=product, per_page=9)
        products_paginator = paginator.page(page)
        return Response({'category':Category.objects.all(), 'product': products_paginator, 'price_data':price_data, 'query_data':query_data})

def main(request):



    return render(request, 'main/main.html')







def cool_basket_add(request, product_id):
    if 'username' in request.session:
        pass
    else:
        request.session['username'] = str(uuid.uuid4())
    if 'basket' not in request.session:
        request.session['basket'] = []
    basket = request.session['basket']
    del request.session['basket']
    request.session['basket'] = basket + [product_id]


    product = Product.objects.get(id=product_id)
    baskets = BasketCool.objects.filter(user=request.session['username'], product=product)


    if not baskets.exists():
        BasketCool.objects.create(user=request.session['username'], product=product, quantity=1)

    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def cool_basket_remove(request, basket_id):
    request.session['basket'] = list(filter(lambda x:False if x == basket_id else True,request.session['basket']))
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

main/templates/main/basket.html
{% extends 'layout.html' %}
{% block title %} Basket {% endblock %}
{% block con %}

{% if products %}

<div class="bg-gray-100 h-screen py-8">
    <div class="container mx-auto px-4">
        <h1 class="text-2xl font-semibold mb-4">Shopping Cart</h1>
        <div class="flex flex-col md:flex-row gap-4">
            <div class="md:w-3/4">
                <div class="bg-white rounded-lg shadow-md p-6 mb-4">
                    <table class="w-full">
                        <thead>
                            <tr>
                                <th class="text-left font-semibold">Product</th>
                                <th class="text-left font-semibold">Price</th>
                                <th class="text-left font-semibold">Quantity</th>
                                <th class="text-left font-semibold">Total</th>

                            </tr>
                        </thead>
                        {% for el, value in products  %}

                        <tbody>
                            <tr>
                                <td class="py-4">
                                    <div class="flex items-center">
                                        <img class="h-16 w-16 mr-4" src="{{ value.image.url }}" alt="Product image">
                                        <span class="font-semibold">{{ value.name }}</span>
                                    </div>
                                </td>
                                <td class="py-4">{{ value.price }}</td>
                                <td class="py-4">
                                    <div class="flex items-center">
                                        <div class="col-lg-4">
                                <input name="basketID" type="number" class="form-control"
                                       value='{{ el }}' min="0">
                            </div>
                                    </div>
                                    <a href="{% url  'main:basket_remove' value.id %}"><button class="bg-blue-500 text-white py-2 px-2 rounded-lg mt-4 w-20">Delete</button></a>
                                </td>
                                <td class="py-4">{% widthratio el 1 value.price %}.0000</td>

                            </tr>

                            <!-- More product rows -->
                        </tbody>
                    {% endfor %}
                    </table>
                </div>
            </div>
            <div class="md:w-1/4">
                <div class="bg-white rounded-lg shadow-md p-6">
                    <h2 class="text-lg font-semibold mb-4">Summary</h2>
                    <div class="flex justify-between mb-2">
                        <span>Subtotal</span>
                        <span>{{ total_sum }}</span>
                    </div>

                    <div class="flex justify-between mb-2">
                        <span>Total Quantity</span>
                        <span>{{ total_quantity }}</span>
                    </div>
                    <hr class="my-2">
                    <div class="flex justify-between mb-2">
                        <span class="font-semibold">Total</span>
                        <span class="font-semibold">{{ total_sum }}</span>
                    </div>
                    <button class="bg-blue-500 text-white py-2 px-4 rounded-lg mt-4 w-full">Checkout</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">

    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Корзина Пуста</h1>
      <p class="mb-8 leading-relaxed">Вы еще не добавили товары в корзину</p>
      <div class="flex justify-center">
        <a href="{% url 'main:menu' %}"> <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Перейти к покупке</button> </a>

      </div>
    </div>
  </div>
</section>
{% endif %}
{% endblock%}

main/templates/main/detail.html
{% extends 'layout.html' %}
{% block title %}
{{ food.name }}
{% endblock %}
{% block con %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">BRAND NAME</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ product.name}}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>

        </div>
        <p class="leading-relaxed mb-4">{{ product.info }}</p>

        </div>
        <div class="flex">
          <span class="title-font font-medium text-2xl text-gray-900">{{ product.price }}</span>
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Buy</button>
          <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="{{ product.image.url }}">
    </div>
  </div>

</section>
<p class="price">${{ product.price }}</p>
<form action="{% url "cart:cart_add" product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Add to cart">
</form>
{% endblock %}

main/templates/main/menu.html
{% extends 'layout.html' %}
{% block title %}
Menu
{% endblock title %}

{% block con %}
<!-- component -->




<div class="w-2/12 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white">
    <a href="#" aria-current="true" class="block w-full px-4 py-2 text-white bg-blue-700 border-b border-gray-200 rounded-t-lg cursor-pointer dark:bg-gray-800 dark:border-gray-600">
        Сategory
    </a>
    {% for el in category%}
    <a href="{{ el.get_absolute_url }}" class="block w-full px-4 py-2 border-b border-gray-200 cursor-pointer hover:bg-gray-100 hover:text-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:border-gray-600 dark:hover:bg-gray-600 dark:hover:text-white dark:focus:ring-gray-500 dark:focus:text-white">
        {{ el.name }}
    </a>
    {% endfor %}


</div>

<!-- TW Elements is free under AGPL, with commercial license required for specific uses. See more details: https://tw-elements.com/license/ and contact us for queries at tailwind@mdbootstrap.com -->
<div class="w-3/12 ">
<div class="max-w-2xl mx-auto">
<form>
	<label for="countries" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400">Select an option</label>
        <select  name="sort_method" id="countries" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        <option selected>Выберите способ сортировки</option>
        <option value="up">По возростанию цены</option>
        <option value="down">По убыванию цены</option>

    </select>



    <div class="mb-3">
<label for="max-range" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Max:<span id="max"></span>$</label>
<input {% if query_data.max_price %} value="{{ query_data.max_price }}" {% endif %} id="max-range" name="max_price" min="{{ price_data.min_price }}" max="{{ price_data.max_price }}" type="range"  class="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700">

<label for="min-range" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Min:<span id="min">$</span></label>
<input  id="min-range"  {% if query_data.min_price %} value="{{ query_data.min_price }}" {% endif %} name='min_price' min="{{ price_data.min_price }}" max="{{ price_data.max_price }}" type="range"  class="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700">
<script>
  var slider = document.getElementById("min-range");
  var output = document.getElementById("min");
  output.innerHTML = slider.value; // Отображение начального значения слайдера

  // Обновление значения слайдера при перемещении ползунка
  slider.oninput = function() {
    output.innerHTML = this.value;
  }
</script>

<script>
  var slider = document.getElementById("max-range");
  var output = document.getElementById("max");
  output.innerHTML = slider.value; // Отображение начального значения слайдера

  // Обновление значения слайдера при перемещении ползунка
  slider.oninput = function() {
    output.innerHTML = this.value;
  }
</script>



  <div class="relative mb-4 flex  flex-wrap items-stretch">
    <input
      {% if query_data.search_value %}
      value="{{ query_data.search_value }}"
      {% endif %}
            name="search"
      type="search"
      class="relative m-0 -mr-0.5 block min-w-0 flex-auto rounded-l border border-solid border-neutral-300 bg-transparent bg-clip-padding px-3 py-[0.25rem] text-base font-normal leading-[1.6] text-neutral-700 outline-none transition duration-200 ease-in-out focus:z-[3] focus:border-primary focus:text-neutral-700 focus:shadow-[inset_0_0_0_1px_rgb(59,113,202)] focus:outline-none dark:border-neutral-600 dark:text-neutral-200 dark:placeholder:text-neutral-200 dark:focus:border-primary"
      placeholder="Search"
      aria-label="Search"
      aria-describedby="button-addon1" />

    <!--Search button-->
    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
  Search
</button>
  </div>
</div>
    </div>
    </form>


</div>


<!-- source: https://github.com/mfg888/Responsive-Tailwind-CSS-Grid/blob/main/index.html -->


{% if product %}
<!-- ✅ Grid Section - Starts Here 👇 -->
<section id="Projects"
    class="w-fit mx-auto grid grid-cols-1 lg:grid-cols-3 md:grid-cols-2 justify-items-center justify-center gap-y-20 gap-x-14 mt-10 mb-5">
{% for el in product %}
    <!--   ✅ Product card 1 - Starts Here 👇 -->
    <div class="w-72 bg-white shadow-md rounded-xl duration-500 hover:scale-105 hover:shadow-xl">
        <a href="#">
            <img src="{{ el.image.url }}"
                    alt="Product" class="h-80 w-72 object-cover rounded-t-xl" />
            <div class="px-4 py-3 w-72">
                <span class="text-gray-400 mr-3 uppercase text-xs">Brand</span>
                <p class="text-lg font-bold text-black truncate block capitalize">{{ el.name }}</p>
                <div class="flex items-center">
                    <p class="text-lg font-semibold text-black cursor-auto my-3">{{ el.price }}$</p>
                    <del>

                    <a href="{% url 'main:basket_add' el.id %}"> <div class="ml-auto"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                            fill="currentColor" class="bi bi-bag-plus" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M8 7.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0v-1.5H6a.5.5 0 0 1 0-1h1.5V8a.5.5 0 0 1 .5-.5z" />
                            <path
                                d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z" />
                        </svg></div></a>
                </div>
            </div>
        </a>
    </div>

{% endfor %}
</section>


<!-- Support Me 🙏🥰 -->
<script src="https://storage.ko-fi.com/cdn/scripts/overlay-widget.js"></script>
<script>
    kofiWidgetOverlay.draw('mohamedghulam', {
            'type': 'floating-chat',
            'floating-chat.donateButton.text': 'Support me',
            'floating-chat.donateButton.background-color': '#323842',
            'floating-chat.donateButton.text-color': '#fff'
        });
</script>
<nav aria-label="Page navigation example">
  <ul class=" justify-center inline-flex -space-x-px text-sm">
    <li>
      <a href="{% if product.has_previous %}{% url 'main:paginator' product.previous_page_number %}{% else%} # {% endif %}" class="flex items-center justify-center px-3 h-8 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white {% if not product.has_previos %} disabled {% endif%}">Previous</a>
    </li>
    {% for page in product.paginator.page_range %}

    <li>
      <a href="{% url 'main:paginator' page %}" class="flex items-center justify-center px-4 h-10 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white  {% if not product.has_previos %} disabled {% endif%}">{{ page}}</a>
    </li>
    {% endfor %}

    <li>
      <a href="{% if product.has_next %}{% url 'main:paginator' product.next_page_number %}{% else%} # {% endif %}" class="flex items-center justify-center px-4 h-10 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white  {% if not product.has_previos %} disabled {% endif%}">Next</a>
    </li>
  </ul>
</nav>

{% else %}
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">

    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Здесь пока что нет продуктов!</h1>

      <div class="flex justify-center">
        <a href="{% url 'main:main' %}"> <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Перейти на Главную страницу</button> </a>

      </div>
    </div>
  </div>
</section>

<!-- 🛑 Grid Section - Ends Here -->



{% endif %}
{% endblock con %}

main/templates/main/products.html
{% if basket  %}
<h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Корзина <span class="badge badge-secondary badge-pill">{{ basket.total_quantity }}</span>
            </h4>
{% for el in basket %}
<div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ el.product.name }}</h5>
                    <p class="card-text">{{ el.product.anons}}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="basketID" type="number" class="form-control"
                                       value="{{ el.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">{{ el.sum }} сум</div>
                            <div class="col-lg-4">
                                <a class="btn btn-success btn-lg float-right" href="{% url  'main:basket_remove' el.id %}">
                Удалить
            </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
{% endfor %}
<div class="card mb-3">
                <div class="card-footer">
                    <p class="float-left">Итого</p>
                    <h4 class="float-right">{{ basket.total_sum }} сум.</h4>
                </div>
            </div>
            <a class="btn btn-success btn-lg float-right" href="../orders/order-create.html">
                Оформить заказ
            </a>
        </div>
    </div>
{% else %}
<h4 class="mt-3 mb-3 text-center">
        Корзина пуста
    </h4>
{% endif %}